(() => {
const firestoreCollections = {
  clientes: {
    purpose: "Registrar clientes naturales, empresas y flotas.",
    keyFields: ["id", "nombre", "telefono", "tipoCliente", "ruc"],
  },
  vehiculos: {
    purpose: "Asociar placas, marcas, modelos, VIN y kilometraje a cada cliente.",
    keyFields: ["id", "clienteId", "placa", "marca", "modelo", "anio", "kilometraje"],
  },
  ordenes_trabajo: {
    purpose: "Centralizar el flujo operativo, estados, montos e historial de cambios.",
    keyFields: ["id", "clienteId", "vehiculoId", "estado", "fechaIngreso", "montoTotal", "mecanicoId"],
  },
  servicios: {
    purpose: "Catalogar servicios frecuentes para presupuestos e indicadores.",
    keyFields: ["id", "nombre", "categoria", "precioBase"],
  },
  usuarios: {
    purpose: "Controlar accesos por rol administrativo u operativo.",
    keyFields: ["id", "nombre", "rol", "activo"],
  },
};

const mechanics = [
  { id: "mec-01", nombre: "Carlos Palomino", especialidad: "Diagnostico OBD-II" },
  { id: "mec-02", nombre: "Jorge Huaman", especialidad: "Mantenimiento preventivo" },
  { id: "mec-03", nombre: "Luis Tasayco", especialidad: "Frenos y suspension" },
  { id: "mec-04", nombre: "Miguel Rojas", especialidad: "Sistema electrico" },
];

const clients = [
  { id: "cli-01", nombre: "Transportes Chincha Sur", tipoCliente: "Flota", telefono: "956 420 118" },
  { id: "cli-02", nombre: "Diana Palomino", tipoCliente: "Particular", telefono: "945 110 884" },
  { id: "cli-03", nombre: "Agroexportadora San Miguel", tipoCliente: "Empresa", telefono: "927 602 412" },
  { id: "cli-04", nombre: "Luis Cardenas", tipoCliente: "Particular", telefono: "987 340 225" },
  { id: "cli-05", nombre: "Servicios Logisur", tipoCliente: "Flota", telefono: "933 873 110" },
  { id: "cli-06", nombre: "Maria Quispe", tipoCliente: "Particular", telefono: "958 812 607" },
  { id: "cli-07", nombre: "Constructora Huarango", tipoCliente: "Empresa", telefono: "961 209 554" },
];

const orders = [
  {
    id: "OT-2026-0601",
    clienteId: "cli-01",
    clienteNombre: "Transportes Chincha Sur",
    placa: "A8F-312",
    marcaModelo: "Toyota Hilux 2021",
    servicio: "Mantenimiento preventivo 10K",
    categoria: "Mantenimiento",
    mecanicoId: "mec-02",
    mecanicoNombre: "Jorge Huaman",
    estado: "Entregado",
    fechaIngreso: "2026-06-03T08:20:00",
    fechaEntrega: "2026-06-03T15:40:00",
    kilometraje: 84200,
    montoTotal: 480,
    fallaReportada: "Revision programada de flota.",
    trabajoRealizado: "Cambio de aceite, filtros, revision de frenos y escaneo OBD-II.",
    historial: [
      "08:20 Recepcion y registro de evidencia inicial.",
      "09:10 Asignacion a mantenimiento preventivo.",
      "15:40 Entrega validada por encargado.",
    ],
  },
  {
    id: "OT-2026-0602",
    clienteId: "cli-02",
    clienteNombre: "Diana Palomino",
    placa: "B4M-781",
    marcaModelo: "Kia Rio 2019",
    servicio: "Diagnostico por check engine",
    categoria: "Diagnostico",
    mecanicoId: "mec-01",
    mecanicoNombre: "Carlos Palomino",
    estado: "Entregado",
    fechaIngreso: "2026-06-03T09:45:00",
    fechaEntrega: "2026-06-04T12:15:00",
    kilometraje: 61120,
    montoTotal: 260,
    fallaReportada: "Testigo check engine encendido.",
    trabajoRealizado: "Escaneo OBD-II, limpieza de sensor MAF y prueba de ruta.",
    historial: [
      "09:45 Registro de falla reportada.",
      "10:30 Escaneo y lectura de codigo P0101.",
      "12:15 Vehiculo entregado sin alerta activa.",
    ],
  },
  {
    id: "OT-2026-0603",
    clienteId: "cli-03",
    clienteNombre: "Agroexportadora San Miguel",
    placa: "C7P-448",
    marcaModelo: "Nissan Frontier 2020",
    servicio: "Revision de suspension",
    categoria: "Suspension",
    mecanicoId: "mec-03",
    mecanicoNombre: "Luis Tasayco",
    estado: "Listo",
    fechaIngreso: "2026-06-04T08:10:00",
    fechaEntrega: "2026-06-05T16:10:00",
    kilometraje: 97340,
    montoTotal: 780,
    fallaReportada: "Ruido en tren delantero.",
    trabajoRealizado: "Cambio de bujes, alineamiento y ajuste de pernos.",
    historial: [
      "08:10 Recepcion y fotografias iniciales.",
      "11:25 Presupuesto aprobado por empresa.",
      "16:10 Trabajo finalizado, pendiente de recojo.",
    ],
  },
  {
    id: "OT-2026-0604",
    clienteId: "cli-04",
    clienteNombre: "Luis Cardenas",
    placa: "D2K-905",
    marcaModelo: "Hyundai Accent 2018",
    servicio: "Cambio de pastillas y liquido de frenos",
    categoria: "Frenos",
    mecanicoId: "mec-03",
    mecanicoNombre: "Luis Tasayco",
    estado: "Entregado",
    fechaIngreso: "2026-06-04T10:05:00",
    fechaEntrega: "2026-06-04T14:25:00",
    kilometraje: 73200,
    montoTotal: 390,
    fallaReportada: "Pedal bajo y vibracion al frenar.",
    trabajoRealizado: "Cambio de pastillas delanteras, purga y prueba de frenado.",
    historial: [
      "10:05 Recepcion con evidencia de estado inicial.",
      "11:00 Diagnostico de frenos.",
      "14:25 Entrega con prueba de ruta.",
    ],
  },
  {
    id: "OT-2026-0605",
    clienteId: "cli-05",
    clienteNombre: "Servicios Logisur",
    placa: "E9T-226",
    marcaModelo: "Chevrolet N300 2022",
    servicio: "Mantenimiento preventivo de flota",
    categoria: "Mantenimiento",
    mecanicoId: "mec-02",
    mecanicoNombre: "Jorge Huaman",
    estado: "Entregado",
    fechaIngreso: "2026-06-05T08:35:00",
    fechaEntrega: "2026-06-05T17:05:00",
    kilometraje: 50210,
    montoTotal: 520,
    fallaReportada: "Servicio programado.",
    trabajoRealizado: "Aceite, filtros, revision electrica y control de fluidos.",
    historial: [
      "08:35 Orden creada desde recepcion.",
      "12:50 Presupuesto validado.",
      "17:05 Entrega cerrada.",
    ],
  },
  {
    id: "OT-2026-0606",
    clienteId: "cli-06",
    clienteNombre: "Maria Quispe",
    placa: "F3L-612",
    marcaModelo: "Suzuki Swift 2020",
    servicio: "Revision de sistema electrico",
    categoria: "Electrico",
    mecanicoId: "mec-04",
    mecanicoNombre: "Miguel Rojas",
    estado: "En Proceso",
    fechaIngreso: "2026-06-06T09:15:00",
    fechaEntrega: null,
    kilometraje: 43800,
    montoTotal: 310,
    fallaReportada: "Descarga de bateria durante la noche.",
    trabajoRealizado: "Medicion de consumo parasitario en proceso.",
    historial: [
      "09:15 Recepcion con fotografia de bateria.",
      "10:30 Prueba de alternador aprobada.",
      "15:20 Medicion de consumo en reposo.",
    ],
  },
  {
    id: "OT-2026-0607",
    clienteId: "cli-07",
    clienteNombre: "Constructora Huarango",
    placa: "G6R-044",
    marcaModelo: "Mitsubishi L200 2021",
    servicio: "Diagnostico de perdida de potencia",
    categoria: "Diagnostico",
    mecanicoId: "mec-01",
    mecanicoNombre: "Carlos Palomino",
    estado: "En Proceso",
    fechaIngreso: "2026-06-06T11:40:00",
    fechaEntrega: null,
    kilometraje: 110420,
    montoTotal: 460,
    fallaReportada: "Perdida de potencia en subida.",
    trabajoRealizado: "Escaneo OBD-II y revision de admision en proceso.",
    historial: [
      "11:40 Registro de unidad de empresa.",
      "12:30 Escaneo sin codigos permanentes.",
      "16:00 Prueba de presion de turbo pendiente.",
    ],
  },
  {
    id: "OT-2026-0608",
    clienteId: "cli-01",
    clienteNombre: "Transportes Chincha Sur",
    placa: "H1X-733",
    marcaModelo: "Toyota Hiace 2022",
    servicio: "Cambio de aceite y filtros",
    categoria: "Mantenimiento",
    mecanicoId: "mec-02",
    mecanicoNombre: "Jorge Huaman",
    estado: "Listo",
    fechaIngreso: "2026-06-07T08:25:00",
    fechaEntrega: "2026-06-07T13:50:00",
    kilometraje: 64200,
    montoTotal: 420,
    fallaReportada: "Servicio preventivo por kilometraje.",
    trabajoRealizado: "Aceite Liqui Moly, filtro de aceite, filtro de aire y revision general.",
    historial: [
      "08:25 Recepcion de unidad de flota.",
      "11:15 Cambio de aceite completado.",
      "13:50 Listo para entrega.",
    ],
  },
  {
    id: "OT-2026-0609",
    clienteId: "cli-04",
    clienteNombre: "Luis Cardenas",
    placa: "D2K-905",
    marcaModelo: "Hyundai Accent 2018",
    servicio: "Alineamiento y balanceo",
    categoria: "Suspension",
    mecanicoId: "mec-03",
    mecanicoNombre: "Luis Tasayco",
    estado: "Entregado",
    fechaIngreso: "2026-06-07T15:00:00",
    fechaEntrega: "2026-06-07T17:10:00",
    kilometraje: 73310,
    montoTotal: 160,
    fallaReportada: "Vibracion a 80 km/h.",
    trabajoRealizado: "Balanceo, alineamiento y prueba de ruta.",
    historial: [
      "15:00 Orden creada por retorno del cliente.",
      "16:15 Correccion de convergencia.",
      "17:10 Entrega cerrada.",
    ],
  },
  {
    id: "OT-2026-0610",
    clienteId: "cli-05",
    clienteNombre: "Servicios Logisur",
    placa: "J8N-510",
    marcaModelo: "Hyundai H1 2020",
    servicio: "Revision de aire acondicionado",
    categoria: "Climatizacion",
    mecanicoId: "mec-04",
    mecanicoNombre: "Miguel Rojas",
    estado: "Pendiente",
    fechaIngreso: "2026-06-08T08:50:00",
    fechaEntrega: null,
    kilometraje: 88100,
    montoTotal: 0,
    fallaReportada: "No enfria en ruta larga.",
    trabajoRealizado: "Pendiente de diagnostico.",
    historial: [
      "08:50 Recepcion y toma de kilometraje.",
      "09:05 Pendiente por bahia electrica.",
    ],
  },
  {
    id: "OT-2026-0611",
    clienteId: "cli-03",
    clienteNombre: "Agroexportadora San Miguel",
    placa: "K5V-219",
    marcaModelo: "Isuzu D-Max 2023",
    servicio: "Mantenimiento preventivo y scanner",
    categoria: "Mantenimiento",
    mecanicoId: "mec-01",
    mecanicoNombre: "Carlos Palomino",
    estado: "En Proceso",
    fechaIngreso: "2026-06-08T10:20:00",
    fechaEntrega: null,
    kilometraje: 36200,
    montoTotal: 540,
    fallaReportada: "Servicio de garantia interna de flota.",
    trabajoRealizado: "Cambio de filtros finalizado, escaneo en proceso.",
    historial: [
      "10:20 Recepcion de unidad.",
      "11:30 Cambio de filtros iniciado.",
      "15:45 Escaneo y revision de codigos.",
    ],
  },
  {
    id: "OT-2026-0612",
    clienteId: "cli-02",
    clienteNombre: "Diana Palomino",
    placa: "L7C-882",
    marcaModelo: "Mazda CX-5 2021",
    servicio: "Revision pre-viaje",
    categoria: "Inspeccion",
    mecanicoId: "mec-02",
    mecanicoNombre: "Jorge Huaman",
    estado: "Entregado",
    fechaIngreso: "2026-06-08T14:10:00",
    fechaEntrega: "2026-06-08T18:00:00",
    kilometraje: 58200,
    montoTotal: 210,
    fallaReportada: "Inspeccion general antes de viaje.",
    trabajoRealizado: "Revision de niveles, frenos, llantas, luces y scanner preventivo.",
    historial: [
      "14:10 Recepcion.",
      "16:50 Inspeccion cerrada.",
      "18:00 Entrega con recomendaciones.",
    ],
  },
  {
    id: "OT-2026-0613",
    clienteId: "cli-06",
    clienteNombre: "Maria Quispe",
    placa: "M9P-064",
    marcaModelo: "Toyota Yaris 2017",
    servicio: "Cambio de amortiguadores",
    categoria: "Suspension",
    mecanicoId: "mec-03",
    mecanicoNombre: "Luis Tasayco",
    estado: "Pendiente",
    fechaIngreso: "2026-06-09T08:05:00",
    fechaEntrega: null,
    kilometraje: 91400,
    montoTotal: 690,
    fallaReportada: "Golpes en parte posterior.",
    trabajoRealizado: "Presupuesto registrado, pendiente de aprobacion.",
    historial: [
      "08:05 Recepcion con evidencia inicial.",
      "08:45 Diagnostico de amortiguadores posteriores.",
    ],
  },
  {
    id: "OT-2026-0614",
    clienteId: "cli-07",
    clienteNombre: "Constructora Huarango",
    placa: "N3D-701",
    marcaModelo: "Toyota Hilux 2022",
    servicio: "Revision de frenos por carga pesada",
    categoria: "Frenos",
    mecanicoId: "mec-04",
    mecanicoNombre: "Miguel Rojas",
    estado: "En Proceso",
    fechaIngreso: "2026-06-09T09:30:00",
    fechaEntrega: null,
    kilometraje: 77550,
    montoTotal: 850,
    fallaReportada: "Ruido y olor al frenar.",
    trabajoRealizado: "Revision de discos y mordazas en proceso.",
    historial: [
      "09:30 Recepcion de vehiculo de obra.",
      "10:25 Desmontaje de ruedas delanteras.",
      "12:10 Validacion de presupuesto enviada.",
    ],
  },
  {
    id: "OT-2026-0615",
    clienteId: "cli-01",
    clienteNombre: "Transportes Chincha Sur",
    placa: "P2S-456",
    marcaModelo: "Toyota Coaster 2019",
    servicio: "Mantenimiento correctivo electrico",
    categoria: "Electrico",
    mecanicoId: "mec-04",
    mecanicoNombre: "Miguel Rojas",
    estado: "Pendiente",
    fechaIngreso: "2026-06-09T13:15:00",
    fechaEntrega: null,
    kilometraje: 126800,
    montoTotal: 0,
    fallaReportada: "Falla intermitente de luces interiores.",
    trabajoRealizado: "Pendiente por agenda del mecanico electrico.",
    historial: [
      "13:15 Unidad ingresada.",
      "13:30 Fotos y accesorios registrados.",
    ],
  },
];

const services = [
  { id: "srv-01", nombre: "Mantenimiento menor" },
  { id: "srv-02", nombre: "Mantenimiento mayor" },
  { id: "srv-03", nombre: "Afinamiento electrónico" },
  { id: "srv-04", nombre: "Suspensión" },
  { id: "srv-05", nombre: "Dirección" },
  { id: "srv-06", nombre: "Reparación de luces delanteras" },
  { id: "srv-07", nombre: "Limpieza de tanque de combustible" },
];

window.MANCURIA_DATA = {
  firestoreCollections,
  mechanics,
  clients,
  orders,
  services,
};
})();
